name: ruskvant_todos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  freezed: 2.4.6
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  json_serializable: 6.7.1
  dio: 5.4.0
  retrofit: 4.0.3
  get: 4.6.1
  get_storage: 2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.1
  build_runner: 2.4.7
  retrofit_generator: 8.0.6

flutter:
  uses-material-design: true

scripts:
  wipe: flutter clean && flutter pub get
  rebuild: dart run build_runner build --delete-conflicting-outputs
